Flags = [
    ("United States", "🇺🇸"),
    ("United Kingdom", "🇬🇧"),
    ("Canada", "🇨🇦"),
    ("Australia", "🇦🇺"),
    ("Germany", "🇩🇪"),
    ("France", "🇫🇷"),
    ("Spain", "🇪🇸"),
    ("Italy", "🇮🇹"),
    ("Japan", "🇯🇵"),
    ("China", "🇨🇳"),
    ("India", "🇮🇳"),
    ("Brazil", "🇧🇷"),
    ("South Korea", "🇰🇷"),
    ("Mexico", "🇲🇽"),
    ("South Africa", "🇿🇦"),
]

Sports = [
    ("basketball", "🏀"),
    ("soccer", "⚽"),
    ("baseball", "⚾"),
    ("tennis", "🎾"),
    ("volleyball", "🏐"),
    ("cricket", "🏏"),
    ("rugby", "🏉"),
    ("golf", "⛳"),
    ("hockey", "🏒"),
    ("swimming", "🏊‍♂️"),
    ("track and field", "🏃‍♀️"),
    ("boxing", "🥊"),
]

Clothing = [
    ("t-shirt", "👕"),
    ("jeans", "👖"),
    ("shorts", "🩳"),
    ("dress", "👗"),
    ("jacket", "🧥"),
    ("hat", "🧢"),
    ("scarf", "🧣"),
    ("socks", "🧦"),
    ("shoes", "👟"),
]

Fruits = [
    ("apple", "🍎"),
    ("banana", "🍌"),
    ("orange", "🍊"),
    ("strawberry", "🍓"),
    ("watermelon", "🍉"),
    ("grape", "🍇"),
    ("pineapple", "🍍"),
    ("kiwi", "🥝"),
    ("mango", "🥭"),
    ("peach", "🍑"),
    ("pear", "🍐"),
    ("cherry", "🍒"),
    ("lemon", "🍋"),
    ("coconut", "🥥"),
    ("melon", "🍈"),
]

Animals = [
    ("cat", "🐈"),
    ("dog", "🐕"),
    ("lion", "🦁"),
    ("tiger", "🐅"),
    ("elephant", "🐘"),
    ("giraffe", "🦒"),
    ("zebra", "🦓"),
    ("monkey", "🐒"),
    ("kangaroo", "🦘"),
    ("hippopotamus", "🦛"),
    ("rhinoceros", "🦏"),
    ("bear", "🐻"),
    ("wolf", "🐺"),
    ("fox", "🦊"),
    ("rabbit", "🐇"),
    ("panda", "🐼"),
    ("koala", "🐨"),
    ("crocodile", "🐊"),
    ("horse", "🐎"),
    ("cow", "🐄"),
    ("swan", "🦢"),
    ("raccoon", "🦝"),
    ("fish", "🐠"),
    ("peacock", "🦚"),
]

Nature = [
    ("evergreen tree", "🌲"),
    ("deciduous tree", "🌳"),
    ("palm tree", "🌴"),
    ("cactus", "🌵"),
    ("seedling", "🌱"),
    ("four leaf clover", "🍀"),
    ("maple leaf", "🍁"),
    ("fallen leaf", "🍂"),
    ("cherry blossom", "🌸"),
    ("rose", "🌹"),
    ("hibiscus", "🌺"),
    ("sunflower", "🌻"),
    ("mushroom", "🍄"),
    ("ear of rice", "🌾"),
    ("shamrock", "☘️"),
]

Foods = [
    ("bread", "🍞"),
    ("bagel", "🥯"),
    ("hamburger", "🍔"),
    ("french fries", "🍟"),
    ("pizza", "🍕"),
    ("hot dog", "🌭"),
    ("taco", "🌮"),
    ("burrito", "🌯"),
    ("sandwich", "🥪"),
    ("pancakes", "🥞"),
    ("waffle", "🧇"),
    ("bacon", "🥓"),
    ("fried shrimp", "🍤"),
    ("sushi", "🍣"),
    ("bento box", "🍱"),
]

HandSymbols = [
    ("thumbs up", "👍"),
    ("thumbs down", "👎"),
    ("clapping hands", "👏"),
    ("folded hands", "🙏"),
    ("victory hand", "✌️"),
    ("raised hand", "✋"),
    ("oncoming fist", "👊"),
    ("handshake", "🤝"),
    ("waving hand", "👋"),
    ("OK hand", "👌"),
    ("pinching hand", "🤏"),
    ("love-you gesture", "🤟"),
    ("middle finger", "🖕"),
    ("call me hand", "🤙"),
    ("sign of the horns", "🤘"),
]

Faces = [
    ("grinning face", "😀"),
    ("grinning face with big eyes", "😃"),
    ("grinning face with smiling eyes", "😄"),
    ("beaming face with smiling eyes", "😁"),
    ("face with tears of joy", "😂"),
    ("rolling on the floor laughing", "🤣"),
    ("slightly smiling face", "🙂"),
    ("upside-down face", "🙃"),
    ("winking face", "😉"),
    ("smiling face with sunglasses", "😎"),
    ("neutral face", "😐"),
    ("expressionless face", "😑"),
    ("unamused face", "😒"),
    ("thinking face", "🤔"),
    ("face with raised eyebrow", "🤨"),
]

EMOJI_CATEGORIES = {
    "Animals": ["🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸"],
    "Food": ["🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🍈", "🍒", "🍑", "🥭", "🍍", "🥥"],
    "Sports": ["⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱", "🏓", "🏸", "🏒", "⛳"],
    "Weather": ["☀️", "🌤️", "⛅", "🌥️", "☁️", "🌦️", "🌧️", "⛈️", "🌩️", "🌨️", "❄️", "💨", "🌪️", "☔"],
    "Faces": ["😀", "😃", "😄", "😁", "😅", "😂", "🤣", "😊", "😇", "🙂", "🙃", "😉", "😌", "😍"]
}
